# Generated by Django 2.1.7 on 2019-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Genre', models.CharField(max_length=20)),
                ('Download', models.BigIntegerField()),
                ('FileName', models.CharField(max_length=120)),
            ],
        ),
    ]
